### ISSUE TITLE
AttributeError: 'MTNet' object has no attribute 'output_keep_prob'

### ISSUE THREAD

**Issue by lzh66** [Maple728/MTNet#8]
Traceback (most recent call last):
  File "main.py", line 201, in <module>
    run_one_config(config)
  File "main.py", line 147, in run_one_config
    model = MTNet(config)
  File "D:\study\keyan\paper\MTNet-master\models\MTNet.py", line 19, in __init__
    m_is = self.__encoder(X, self.config.n, scope='m')
  File "D:\study\keyan\paper\MTNet-master\models\MTNet.py", line 134, in __encoder
    h_conv1 = tf.nn.dropout(h_conv1, self.output_keep_prob)
AttributeError: 'MTNet' object has no attribute 'output_keep_prob'

**Comment by Alex43975** [comment]
Have U solved this problem yet? 
May I ask how?

**Comment by lgq1997** [comment]
> 你解决了这个问题吗？
> 请问如何？

Excuse me, have U solved this problem yet?

**Comment by Maple728** [comment]
Try move the following two line (line 92, 93)
        self.input_keep_prob = input_keep_prob
        self.output_keep_prob = output_keep_prob
to the position before the model was built (before line 16).

**Comment by Maple728** [comment]
I will fix these bugs when I'm free.

**Comment by lgq1997** [comment]
> Try move the following two line (line 92, 93)
> self.input_keep_prob = input_keep_prob
> self.output_keep_prob = output_keep_prob
> to the position before the model was built (before line 16).

It worked! Thank you very much!
